wisvch:
  connect:
    issuer-uri: https://connect.ch.tudelft.nl/
    client-uri: http://localhost:8080
    admin-groups:
     - chbeheer
    registered-client:
      client-name: CH Kubernetes
      client-id: kubernetes
